# Generated by Django 5.2.10 on 2026-01-25 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nazwa kategorii"),
                ),
            ],
            options={
                "verbose_name_plural": "Kategorie",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Tytuł przepisu"),
                ),
                ("description", models.TextField(verbose_name="Opis przygotowania")),
                (
                    "ingredients",
                    models.TextField(
                        help_text="Wpisz składniki po przecinku",
                        verbose_name="Składniki",
                    ),
                ),
                (
                    "preparation_time",
                    models.PositiveIntegerField(verbose_name="Czas (min)"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Łatwy", "Łatwy"),
                            ("Średni", "Średni"),
                            ("Trudny", "Trudny"),
                        ],
                        default="Easy",
                        max_length=10,
                        verbose_name="Trudność",
                    ),
                ),
                (
                    "is_vegetarian",
                    models.BooleanField(
                        default=False, verbose_name="Czy wegetariańskie?"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="recipes_img/",
                        verbose_name="Zdjęcie",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.category",
                        verbose_name="Kategoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Treść komentarza")),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 gwiazdek"),
                            (2, "2 gwiazdek"),
                            (3, "3 gwiazdek"),
                            (4, "4 gwiazdek"),
                            (5, "5 gwiazdek"),
                        ],
                        verbose_name="Ocena",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
    ]
